PRESET_BASE: interop
CONFIG_NAME: posdocker

MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 3
# MIN_GENESIS_TIME: 1724759349
# GENESIS_DELAY: 15

# # # Genesis
GENESIS_FORK_VERSION: 0x20000089

# # Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# # Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0
# eth_getBlockByNumber 0x0 result.hash
#TERMINAL_BLOCK_HASH: 0x2646fe3fcda55c96a73d0a320cfb46462e17a2ca96c494ffbd5f3fcf31a15d7f
#TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# # Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# #deneb
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093

# Electra
ELECTRA_FORK_VERSION: 0x60000038
ELECTRA_FORK_EPOCH: 100000000

# EIP7594 - Peerdas
# EIP7594_FORK_VERSION: 0x60000039
# EIP7594_FORK_EPOCH: 100000001

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 6

# Deposit contract (PoS)
DEPOSIT_CHAIN_ID: 14800
DEPOSIT_NETWORK_ID: 14800
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242